server:
  port: 6112

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: ownDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost/bpm_flow?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 1
      max-active: 20
  tomcat:
    uri-encoding: UTF-8

  thymeleaf:
    cache: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
